   version: '3.8'

   services:
    mosquitto:
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      restart: unless-stopped
      ports:
        - "1883:1883"
        - "9001:9001"
      expose:
        - 1883
        - 9001
      volumes:
        - ./mosquitto:/etc/mosquitto
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      privileged: true
      ports:
        - "8080:8080"
      volumes:
        - ./data:/app/data
      depends_on:
        - mosquitto
      restart: always
